/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package log4j_V2;

import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Iterator;
import java.util.Properties;
import java.util.Set;
import javax.swing.JFileChooser;

/**
 *
 * @author kamal64
 */
public class NewJFrame extends javax.swing.JFrame {
    private static Set propKeySet;

    private JFileChooser fc;
    private String logFileLocation;
    private String conversionPattern;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log4jFileTextField = new javax.swing.JTextField();
        PropertyFileBrowse = new javax.swing.JButton();
        logFileTextField = new javax.swing.JTextField();
        logFileBrowse = new javax.swing.JButton();
        log4jFileMessage = new javax.swing.JLabel();
        logFileParserButton = new javax.swing.JButton();
        logFileMessage = new javax.swing.JLabel();
        level = new javax.swing.JComboBox();
        result = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PropertyFileBrowse.setText("lorjPropertyFile Browse");
        PropertyFileBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PropertyFileBrowseActionPerformed(evt);
            }
        });

        logFileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logFileTextFieldActionPerformed(evt);
            }
        });

        logFileBrowse.setText("logFile Browse");
        logFileBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logFileBrowseActionPerformed(evt);
            }
        });

        log4jFileMessage.setBackground(new java.awt.Color(255, 255, 255));
        log4jFileMessage.setText("log4jFileMessage");

        logFileParserButton.setText("Parse File");
        logFileParserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logFileParserButtonActionPerformed(evt);
            }
        });

        logFileMessage.setText("logFileMessage");

        level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "DEBUG", "ERROR", "WARN" }));

        result.setText("Result");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        jLabel1.setText("Log4j File");

        jLabel2.setText("Log File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel1)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(log4jFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(logFileMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(log4jFileMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                .addComponent(logFileTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PropertyFileBrowse)
                            .addComponent(logFileBrowse)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(logFileParserButton)
                        .addGap(54, 54, 54)
                        .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(result)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log4jFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PropertyFileBrowse)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(log4jFileMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logFileBrowse)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logFileMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logFileParserButton)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logFileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logFileTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logFileTextFieldActionPerformed

    private void PropertyFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PropertyFileBrowseActionPerformed
        log4jFileMessage.setText("");
        if (fc == null) {
            fc = new JFileChooser();

            //Add a custom file filter and disable the default
            //(Accept All) file filter.
            fc.addChoosableFileFilter(new ImageFilter());
            fc.setAcceptAllFileFilterUsed(false);

            //Add custom icons for file types.
            fc.setFileView(new ImageFileView());

            //Add the preview pane.
            fc.setAccessory(new ImagePreview(fc));
        }

        int returnVal = fc.showDialog(new FileChooserDemo2(), "Attach");
        File file = null;
        //Process the results.
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();
        }
        if(file==null)
            return ;
        log4jFileTextField.setText(file.getAbsolutePath());

        boolean properFileFlag = checkPropertyFile(file);
        if (properFileFlag) {
            log4jFileMessage.setForeground(Color.BLACK);
            log4jFileMessage.setText("Property File Loaded successfully");
        }
        else{
            log4jFileMessage.setForeground(Color.RED);
            log4jFileMessage.setText("Please provide valid log4j property file");
        }

        //Reset the file chooser for the next time it's shown.
        fc.setSelectedFile(null);
    }//GEN-LAST:event_PropertyFileBrowseActionPerformed

    private void logFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logFileBrowseActionPerformed

        if (fc == null) {
            fc = new JFileChooser();

            //Add a custom file filter and disable the default
            //(Accept All) file filter.
            fc.addChoosableFileFilter(new ImageFilter());
            fc.setAcceptAllFileFilterUsed(false);

            //Add custom icons for file types.
            fc.setFileView(new ImageFileView());

            //Add the preview pane.
//            fc.setAccessory(new ImagePreview(fc));
        }

        int returnVal = fc.showDialog(new FileChooserDemo2(), "Attach");
        File file = null;
        //Process the results.
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fc.getSelectedFile();

        }
        logFileLocation= file.getAbsolutePath();
        String logFileName = "";
        logFileTextField.setText(logFileLocation);

        if (logFileLocation.contains("/")) {
            String temp[] = logFileLocation.split("/");
            if (!(temp[temp.length - 1].contains("/") || temp[temp.length - 1]
                    .contains("\\"))) {
                logFileName = temp[temp.length - 1];
            }
            System.out.println("first if condition >> " + logFileName);
        }
        if (logFileLocation.contains("\\")) {
            String temp[] = logFileLocation.split("\\\\");
            if (!(temp[temp.length - 1].contains("/") || temp[temp.length - 1]
                    .contains("\\"))) {
                logFileName = temp[temp.length - 1];
            }
            System.out.println("second if condition >> " + logFileName);
        }
        fc.setSelectedFile(null);
    }//GEN-LAST:event_logFileBrowseActionPerformed

    private void logFileParserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logFileParserButtonActionPerformed
        LogParserAdv1.beginOperation(System.currentTimeMillis(), conversionPattern ,logFileLocation);
    }//GEN-LAST:event_logFileParserButtonActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        String levelS=(String) level.getSelectedItem();
        if(levelS.equalsIgnoreCase("select")){
            System.out.println("please select level");
            return ;
        }
        String [] arg=new String[1];
        arg[0]=levelS;
        GridView.main(arg);
    }//GEN-LAST:event_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PropertyFileBrowse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox level;
    private javax.swing.JLabel log4jFileMessage;
    private javax.swing.JTextField log4jFileTextField;
    private javax.swing.JButton logFileBrowse;
    private javax.swing.JLabel logFileMessage;
    private javax.swing.JButton logFileParserButton;
    private javax.swing.JTextField logFileTextField;
    private javax.swing.JButton result;
    // End of variables declaration//GEN-END:variables

    private boolean checkPropertyFile(File propertieFile) {
        boolean properFileFlag = true;
        Properties props = new Properties();
        String reqKey = "";
        boolean foundConversionPattern=false;
        try {
            FileInputStream fis = new FileInputStream(propertieFile);
            // read the property file
            props.load(fis);

            // getting key set from file, saving key set for later iteration
            NewJFrame.propKeySet = props.keySet();

            // if file don't begin with log4j standard key format return false
            if(! ( propKeySet.toArray()[0].toString().toLowerCase().contains("log4j") ) ){
                System.out.println(propKeySet.toArray()[0].toString());
                return false;
            }
            System.out.println("whle key set :: "+propKeySet.toString());
            String fileAppenderrKey="";
            // first iteration through property file to get req. key
            for (Iterator iterator1 = propKeySet.iterator(); iterator1 .hasNext();) {
                String key = (String) iterator1.next();
                
                if (props.getProperty(key).toLowerCase().endsWith("fileappender")) {
                    System.out.println("in fileappedner>> " + key);
                    fileAppenderrKey = key;
                    
//                    System.out.println("prop chcek>> " + props.getProperty(key + ".File"));
//
//                    if (props.getProperty(key + ".File").toLowerCase()
//                            .endsWith(logFileName)) {
//                        System.out.println("Got required key, breaking >>" + key);
//                        reqKey = key;
//                        foundReqKeyFlag = true;
//                        break;
//                    }
                }
                if(key.equalsIgnoreCase(fileAppenderrKey+".layout.conversionPattern"))
                { System.out.println("key>> "+key);
                conversionPattern = props.getProperty(key);

                    System.out.println("req. conversion pattern is " + conversionPattern);
                foundConversionPattern=true;
                }
            }

            // method return if conversion pattern is found, if not probably key's not properly ordered
            if(foundConversionPattern){
                return true;
            }
            
            // second iteration to get conversion pattern
            for (Iterator iterator2 = NewJFrame.propKeySet.iterator(); iterator2.hasNext();) {

                String key = (String) iterator2.next();

                System.out.println(key + "<< >>" + props.getProperty(key));

                if (key.startsWith(reqKey) && key.toLowerCase().contains((".layout.conversionpattern"))) {
                    // System.out.println(object1);
                    conversionPattern = props.getProperty(key);

                    System.out.println("req. conversion pattern is " + conversionPattern);
                    properFileFlag = true;
                    break;
                }
            }

            // very essential close of input stream.
            fis.close();

        } catch (IOException e) {
            e.printStackTrace();
        }
        return properFileFlag;
    }
}
